### PR TITLE
Cndit 669 keycloak

### PR DESCRIPTION
**Pull request by ssathiah**
Implementation for auth service using Keycloak as Idp.
For the development, used the keycloak server that is installed in the FTS2 AWS environment, and unit testing has been completed.
This PR is mainly to see if the code coverage is sufficient for the SonarCould scan.

### CODE REVIEW

**Comment by ssathiah** [comment]
The user registration module has been removed as it's not required.

**Review by rshanmugam-enquizit — APPROVED** [review]
lgtm

**Review by rshanmugam-enquizit — CHANGES_REQUESTED** [review]
Can you also check to remove the `public.pem` file from the `/resources/certs/` directory? I remember it was also a part of old auth mechanism.

**Comment by ssathiah** [comment]
> Can you also check to remove the `public.pem` file from the `/resources/certs/` directory? I remember it was also a part of old auth mechanism.

Removed the public.pem

**Review by rshanmugam-enquizit — APPROVED** [review]

**Pull request merged**
